// Copyright (c) 2026 Rune Suy and the 2XD2-Engine contributors.
// Licensed under the MIT License.
//

//
// Created by rune-suy on 1/26/26.
//

#ifndef INC_2XD2_ENGINE_NOTIFICATIONS_HPP
#define INC_2XD2_ENGINE_NOTIFICATIONS_HPP

enum Notification
{
    NOTIFICATION_VISIBILITY_TRUE,
    NOTIFICATION_VISIBILITY_FALSE,
    NOTIFICATION_CREATE,
    NOTIFICATION_DESTROY,
    NOTIFICATION_UPDATE,
    NOTIFICATION_PHYSICS_UPDATE,
    NOTIFICATION_DRAW,
    NOTIFICATION_LAYOUT_CHANGED,
};

#endif //INC_2XD2_ENGINE_NOTIFICATIONS_HPP